all:
	gcc ../src/vector.c vector_test.c -o vector -std=c99
	gcc ../src/stack.c stack_test.c -o stack -std=c99
	gcc ../src/llist.c llist_test.c -o llist -std=c99
	gcc ../src/dllist.c dllist_test.c -o dllist -std=c99

vector:	
	gcc ../src/vector.c vector_test.c -o vector -std=c99

stack:
	gcc ../src/stack.c stack_test.c -o stack -std=c99

llist:
	gcc ../src/llist.c llist_test.c -o llist -std=c99

dllist:
	gcc ../src/dllist.c dllist_test.c -o dllist -std=c99

clean:
	rm -f vector stack llist dllist 
